In [1]:
#IMPORTS 
import sys
import numpy as np
import matplotlib.pyplot as plt
sys.path.append(r"C:\Users\DGaard\Desktop\Gits\MoleculeSim\ownSim")

import molecules as mc
import forces as fc
import random
import copy

# Spawn grid molecules

In [2]:
import itertools
def grid_points(box_size,radius, spacing):
  x = np.arange(radius + spacing, box_size[0]- radius- spacing, step = 2*radius + spacing)
  y = np.arange(radius+ spacing, box_size[1]- radius- spacing, step = 2*radius + spacing)
  z = np.arange(radius+ spacing, box_size[2]- radius- spacing, step = 2*radius + spacing)
  all_combinations = list(itertools.product(x,y,z))
  print(x,y,z)
  return [np.array(comb) for comb in all_combinations]

In [3]:

box_size = np.array([1000.,1000.,800.])
radius = 100.
spacing = 50
seed = 42
combs = grid_points(box_size, radius, spacing)
molecules = [mc.Molecule(pos, radius) for pos in combs]
uni = mc.SimpleUniverse(box_size, len(molecules), np.repeat(radius,len(molecules)), seed, own_molecules= molecules)
state = uni.get_state()
print(state)

[150. 400. 650.] [150. 400. 650.] [150. 400.]
[[150. 150. 150.]
 [150. 150. 400.]
 [150. 400. 150.]
 [150. 400. 400.]
 [150. 650. 150.]
 [150. 650. 400.]
 [400. 150. 150.]
 [400. 150. 400.]
 [400. 400. 150.]
 [400. 400. 400.]
 [400. 650. 150.]
 [400. 650. 400.]
 [650. 150. 150.]
 [650. 150. 400.]
 [650. 400. 150.]
 [650. 400. 400.]
 [650. 650. 150.]
 [650. 650. 400.]]


In [4]:
# MAYAVI IMPORTS
import traits
from mayavi import mlab
import numpy as np
from __future__ import absolute_import, division, print_function
from mayavi import mlab
import numpy as np
import math

********************************************************************************
         to build the TVTK classes (9.2). This may cause problems.
         Please rebuild TVTK.
********************************************************************************



In [5]:
#params
num_steps = 20000

In [6]:
points = []

# Perform Simulation
for i in range(num_steps):
  #randomly select a molecule
  mol = uni.select_molecule()
  #keep proposing new steps until one is accepted
  mc.step(uni,mol)
  #store intermediate results?
  points.append(uni.get_state())


#points shape = 20x20x3


C:\Users\DGaard\Desktop\Gits\MoleculeSim\ownSim\forces.py:48: RuntimeWarning: invalid value encountered in log
  thrd_term = np.log((r2 - square_p)/(r2 - square_n))
C:\Users\DGaard\Desktop\Gits\MoleculeSim\ownSim\forces.py:80: RuntimeWarning: invalid value encountered in scalar power
  snd = 28 * (y**(-1/4) - 1)
C:\Users\DGaard\Desktop\Gits\MoleculeSim\ownSim\forces.py:81: RuntimeWarning: invalid value encountered in scalar power
  trd = (20/11) * (1 - y**(11/4))


In [9]:
plt = mlab.points3d(points[0][:, 0], points[0][:, 1], points[0][:, 2])

@mlab.animate(delay=100, ui = True)
def anim():
    f = mlab.gcf()
    while True:
        #temp = "step: "
        for step in range(num_steps):
            temp = "step: " + str(step)
            #print(temp, end = "\r")
            x = points[step][:, 0]
            y = points[step][:, 1]
            z = points[step][:, 2]
        #for (x, y, z) in zip(xs, ys, zs):
            plt.mlab_source.set(x=x, y=y, z=z)
            mlab.text3d(box_size[0],box_size[1],box_size[2], text = temp)
            yield


anim()
mlab.show()

# Spawn random molecules montecarlo style

In [8]:
import numpy as np

def generate_spheres(num_spheres, box_dimensions, radii):
    spheres = []
    box_min = np.array([0, 0, 0])
    box_max = np.array(box_dimensions)

    def check_overlap(new_sphere, existing_spheres):
        for sphere in existing_spheres:
            distance = np.linalg.norm(new_sphere[:3] - sphere[:3])
            if distance < new_sphere[3] + sphere[3]:
                return True
        return False

    for i in range(num_spheres):
        radius = radii[i]
        position = np.random.uniform(box_min + radius, box_max - radius)
        new_sphere = np.append(position, radius)

        while check_overlap(new_sphere, spheres):
            position = np.random.uniform(box_min + radius, box_max - radius)
            new_sphere = np.append(position, radius)

        spheres.append(new_sphere)

    return spheres

# Example usage:
num_spheres = 10
box_dimensions = [10, 10, 10]  # Define the box dimensions [x, y, z]
min_radius = 0.5
max_radius = 2.0

resulting_spheres = generate_spheres(num_spheres, box_dimensions, min_radius, max_radius)
for idx, sphere in enumerate(resulting_spheres):
    print(f"Sphere {idx + 1}: Position {sphere[:3]}, Radius {sphere[3]}")


TypeError: generate_spheres() takes 3 positional arguments but 4 were given