In [3]:
#IMPORTS 
import sys
import numpy as np
import matplotlib.pyplot as plt
sys.path.append(r"C:\Users\EmilR\Documents\GitHub\MoleculeSim\ownSim")

import molecules as mc
import forces as fc
import random
import copy

# Spawn grid molecules

In [4]:
import itertools
def grid_points(box_size,radius, spacing):
  x = np.arange(radius + spacing, box_size[0]- radius- spacing, step = 2*radius + spacing)
  y = np.arange(radius+ spacing, box_size[1]- radius- spacing, step = 2*radius + spacing)
  z = np.arange(radius+ spacing, box_size[2]- radius- spacing, step = 2*radius + spacing)
  all_combinations = list(itertools.product(x,y,z))
  print(x,y,z)
  return [np.array(comb) for comb in all_combinations]

In [5]:
box_size = np.array([1000.,1000.,800.])
radius = 100.
spacing = 50
seed = 42
combs = grid_points(box_size, radius, spacing)
molecules = [mc.Molecule(pos, radius) for pos in combs]
uni = mc.SimpleUniverse(box_size, len(molecules), np.repeat(radius,len(molecules)), seed, own_molecules= molecules)
state = uni.get_state()
print("pos", molecules[0].pos,type(molecules[0].pos))
print(state)

[150. 400. 650.] [150. 400. 650.] [150. 400.]
pos [150. 150. 150.] <class 'numpy.ndarray'>
[[150. 150. 150.]
 [150. 150. 400.]
 [150. 400. 150.]
 [150. 400. 400.]
 [150. 650. 150.]
 [150. 650. 400.]
 [400. 150. 150.]
 [400. 150. 400.]
 [400. 400. 150.]
 [400. 400. 400.]
 [400. 650. 150.]
 [400. 650. 400.]
 [650. 150. 150.]
 [650. 150. 400.]
 [650. 400. 150.]
 [650. 400. 400.]
 [650. 650. 150.]
 [650. 650. 400.]]


In [6]:
# MAYAVI IMPORTS
import traits
from mayavi import mlab
import numpy as np
from __future__ import absolute_import, division, print_function
from mayavi import mlab
import numpy as np
import math

In [7]:
test = []
for i in range(len(uni.molecules)):
  if all(uni.molecules[i].pos == molecules[i]):
    test.append("same")
  else: 
    test.append("dif")
#print(test)
for i in range(5):
  print(combs[i])
  print(uni.molecules[i].pos)

[150. 150. 150.]
[150. 150. 150.]
[150. 150. 400.]
[150. 150. 400.]
[150. 400. 150.]
[150. 400. 150.]
[150. 400. 400.]
[150. 400. 400.]
[150. 650. 150.]
[150. 650. 150.]


In [8]:
#params
num_steps = 20000

In [9]:
points = []

# Perform Simulation
for i in range(num_steps):
  #randomly select a molecule
  mol = uni.select_molecule()
  #keep proposing new steps until one is accepted
  mc.step(uni,mol)
  #store intermediate results?
  points.append(uni.get_state())


#points shape = 20x20x3


energy -0.13406274615268338 <class 'numpy.float64'>
am i in box? True
im in
energy -0.17024633937214323 <class 'numpy.float64'>
am i in box? True
im in
energy -0.09961369427394938 <class 'numpy.float64'>
am i in box? True
im in
energy -0.0995181544111247 <class 'numpy.float64'>
am i in box? True
im in
energy -0.09949626625801132 <class 'numpy.float64'>
am i in box? True
im in
energy -0.13258301574685818 <class 'numpy.float64'>
am i in box? True
im in
energy -0.10325808142090653 <class 'numpy.float64'>
am i in box? True
im in
energy -0.11108194645880093 <class 'numpy.float64'>
am i in box? True
im in
energy -0.10029473913090917 <class 'numpy.float64'>
am i in box? True
im in
energy -0.1342361924650308 <class 'numpy.float64'>
am i in box? True
im in
energy -0.09705351519502567 <class 'numpy.float64'>
am i in box? True
im in
energy -0.09541584448473894 <class 'numpy.float64'>
am i in box? True
im in
energy -0.14249280971821826 <class 'numpy.float64'>
am i in box? True
im in
energy -0.1323

C:\Users\EmilR\Documents\GitHub\MoleculeSim\ownSim\forces.py:48: RuntimeWarning: invalid value encountered in log
  thrd_term = np.log((r2 - square_p)/(r2 - square_n))
C:\Users\EmilR\Documents\GitHub\MoleculeSim\ownSim\forces.py:80: RuntimeWarning: invalid value encountered in scalar power
  snd = 28 * (y**(-1/4) - 1)
C:\Users\EmilR\Documents\GitHub\MoleculeSim\ownSim\forces.py:81: RuntimeWarning: invalid value encountered in scalar power
  trd = (20/11) * (1 - y**(11/4))


energy -0.2443390159651181 <class 'numpy.float64'>
am i in box? True
im in
energy -0.2580702135767323 <class 'numpy.float64'>
am i in box? True
im in
energy -0.482513599467208 <class 'numpy.float64'>
am i in box? True
im in
energy -0.1674918192161729 <class 'numpy.float64'>
am i in box? True
im in
energy -0.24523108479593114 <class 'numpy.float64'>
am i in box? True
im in
energy -0.32423745053919434 <class 'numpy.float64'>
am i in box? True
im in
energy -0.23791630098563388 <class 'numpy.float64'>
am i in box? True
im in
energy -0.3114782604338109 <class 'numpy.float64'>
am i in box? True
im in
encountered nan energy, converting to 0 (consider fixing this) 

energy 0 <class 'int'>
am i in box? True
im in
encountered nan energy, converting to 0 (consider fixing this) 

energy -0.6725863968388796 <class 'numpy.float64'>
am i in box? True
im in
energy -0.43766036143134884 <class 'numpy.float64'>
am i in box? True
im in
energy -0.3446244655565033 <class 'numpy.float64'>
am i in box? True
i

C:\Users\EmilR\Documents\GitHub\MoleculeSim\ownSim\forces.py:94: RuntimeWarning: overflow encountered in exp
  proba = min(1, np.exp(-Beta*(eNew-ePrev)))


am i in box? True
im in
am i in box? True
im in
am i in box? True
im in
am i in box? True
im in
am i in box? True
im in
am i in box? True
im in
encountered nan energy, converting to 0 (consider fixing this) 

am i in box? True
im in
am i in box? True
im in
am i in box? True
im in
am i in box? True
im in
encountered nan energy, converting to 0 (consider fixing this) 

am i in box? True
im in
am i in box? True
im in
am i in box? True
im in
am i in box? True
im in
am i in box? True
im in
am i in box? True
im in
am i in box? True
im in
encountered nan energy, converting to 0 (consider fixing this) 

am i in box? True
im in
am i in box? True
im in
encountered nan energy, converting to 0 (consider fixing this) 

am i in box? True
im in
am i in box? True
im in
am i in box? True
im in
encountered nan energy, converting to 0 (consider fixing this) 

am i in box? True
im in
encountered nan energy, converting to 0 (consider fixing this) 

am i in box? True
im in
am i in box? True
im in
encountere

KeyboardInterrupt: 

In [21]:
plt = mlab.points3d(points[0][:, 0], points[0][:, 1], points[0][:, 2])

@mlab.animate(delay=100, ui = True)
def anim():
    f = mlab.gcf()
    while True:
        #temp = "step: "
        for step in range(num_steps):
            temp = "step: " + str(step)
            #print(temp, end = "\r")
            x = points[step][:, 0]
            y = points[step][:, 1]
            z = points[step][:, 2]
        #for (x, y, z) in zip(xs, ys, zs):
            #plt.mlab_source.set(x=x, y=y, z=z)
            #mlab.text3d(box_size[0],box_size[1],box_size[2], text = temp)
            yield


anim()
mlab.show()