In [1]:
#IMPORTS 
import sys
import numpy as np
import matplotlib.pyplot as plt
sys.path.append(r"C:\Users\DGaard\Desktop\Gits\MoleculeSim\ownSim")

import molecules as mc
import forces as fc
import random
import copy

# Spawn grid molecules

In [2]:
import itertools
def grid_points(box_size,radius, spacing):
  x = np.arange(radius + spacing, box_size[0]- radius- spacing, step = 2*radius + spacing)
  y = np.arange(radius+ spacing, box_size[1]- radius- spacing, step = 2*radius + spacing)
  z = np.arange(radius+ spacing, box_size[2]- radius- spacing, step = 2*radius + spacing)
  all_combinations = list(itertools.product(x,y,z))
  print(x,y,z)
  return [np.array(comb) for comb in all_combinations]

In [3]:
box_size = np.array([1000.,1000.,800.])
radius = 100.
spacing = 50
seed = 42
combs = grid_points(box_size, radius, spacing)
molecules = [mc.Molecule(pos, radius) for pos in combs]
uni = mc.SimpleUniverse(box_size, len(molecules), np.repeat(radius,len(molecules)), seed, own_molecules= molecules)
state = uni.get_state()
print("pos", molecules[0].pos,type(molecules[0].pos))
print(state)

[150. 400. 650.] [150. 400. 650.] [150. 400.]
pos [150. 150. 150.] <class 'numpy.ndarray'>
[[150. 150. 150.]
 [150. 150. 400.]
 [150. 400. 150.]
 [150. 400. 400.]
 [150. 650. 150.]
 [150. 650. 400.]
 [400. 150. 150.]
 [400. 150. 400.]
 [400. 400. 150.]
 [400. 400. 400.]
 [400. 650. 150.]
 [400. 650. 400.]
 [650. 150. 150.]
 [650. 150. 400.]
 [650. 400. 150.]
 [650. 400. 400.]
 [650. 650. 150.]
 [650. 650. 400.]]


In [4]:
# MAYAVI IMPORTS
import traits
from mayavi import mlab
import numpy as np
from __future__ import absolute_import, division, print_function
from mayavi import mlab
import numpy as np
import math

********************************************************************************
         to build the TVTK classes (9.2). This may cause problems.
         Please rebuild TVTK.
********************************************************************************



In [5]:
test = []
for i in range(len(uni.molecules)):
  if all(uni.molecules[i].pos == molecules[i]):
    test.append("same")
  else: 
    test.append("dif")
#print(test)
for i in range(5):
  print(combs[i])
  print(uni.molecules[i].pos)

[150. 150. 150.]
[150. 150. 150.]
[150. 150. 400.]
[150. 150. 400.]
[150. 400. 150.]
[150. 400. 150.]
[150. 400. 400.]
[150. 400. 400.]
[150. 650. 150.]
[150. 650. 150.]


In [6]:
#params
num_steps = 20000

In [7]:
points = []

# Perform Simulation
for i in range(num_steps):
  #randomly select a molecule
  mol = uni.select_molecule()
  #keep proposing new steps until one is accepted
  mc.step(uni,mol)
  #store intermediate results?
  points.append(uni.get_state())


#points shape = 20x20x3


energy -0.13406274615268338
energy -0.1705275136253907
energy -0.09963625214786682
energy -0.09954491327364615
energy -0.09951700271368864
energy -0.12766499034280507
energy -0.09441723332598324
energy -0.10059208663774294
energy -0.09944814931592137
energy -0.13586109943002292
energy -0.09513273581677006
energy -0.1035674824482812
energy -0.1347577009021732
energy -0.13742063004883126
energy -0.1409720609405306
energy -0.11031190377736114
energy -0.1358003292386905
energy -0.10293063575268656
energy -0.1063870047067217
energy -0.10964559639949832
energy -0.1810741447823363
energy -0.14432100261184216
energy -0.13510269169913725
energy -0.13587874089461408
energy -0.15090889951503583
energy -0.1675455743919626
energy -0.12065547960441936
energy -0.15159991832741887
energy -0.14606113429488793
energy -0.16025799054151416
energy -0.1702102331753192
energy -0.11826663864977678
energy -0.1377785280446354
energy -0.10214299853198003
energy -0.1155693060170421
energy -0.12151111489136208
ene

C:\Users\DGaard\Desktop\Gits\MoleculeSim\ownSim\forces.py:48: RuntimeWarning: invalid value encountered in log
  thrd_term = np.log((r2 - square_p)/(r2 - square_n))
C:\Users\DGaard\Desktop\Gits\MoleculeSim\ownSim\forces.py:80: RuntimeWarning: invalid value encountered in scalar power
  snd = 28 * (y**(-1/4) - 1)
C:\Users\DGaard\Desktop\Gits\MoleculeSim\ownSim\forces.py:81: RuntimeWarning: invalid value encountered in scalar power
  trd = (20/11) * (1 - y**(11/4))


energy -0.07926219425542606
energy -0.04414394084453283
energy -0.1496533405345251
energy -0.13459840214162744
energy -0.1073286525928816
energy -0.08855128384775937
energy -0.10292003925668416
energy -0.0910529185512005
energy -0.07841322427481434
energy -0.07825689702247829
energy -0.12003493065772934
energy nan
energy nan
energy -0.1395367540845271
energy -0.08840770698109009
energy -0.07773514116802001
energy -0.11404083189476022
energy -0.09318428630582483
energy -0.07938182964405884
energy -0.4198816843460506
energy -0.09592698768736696
energy -0.10373261633305801
energy -0.08268968115154997
energy -0.13382143142909972
energy -0.1568929830573709
energy -0.14547995858914273
energy -0.14724478267371396
energy -0.08900226967944133
energy -0.07643412790774082
energy -0.1256781248633958
energy -0.07994842907547897
energy -0.10609912707199311
energy -0.197984304525388
energy -0.07195200871583246
energy -0.1098594173346579
energy -0.27512328079407816
energy -0.10383922213314903
energy -

In [21]:
plt = mlab.points3d(points[0][:, 0], points[0][:, 1], points[0][:, 2])

@mlab.animate(delay=100, ui = True)
def anim():
    f = mlab.gcf()
    while True:
        #temp = "step: "
        for step in range(num_steps):
            temp = "step: " + str(step)
            #print(temp, end = "\r")
            x = points[step][:, 0]
            y = points[step][:, 1]
            z = points[step][:, 2]
        #for (x, y, z) in zip(xs, ys, zs):
            #plt.mlab_source.set(x=x, y=y, z=z)
            #mlab.text3d(box_size[0],box_size[1],box_size[2], text = temp)
            yield


anim()
mlab.show()