In [2]:
#IMPORTS 
import sys
import numpy as np
import matplotlib.pyplot as plt
sys.path.append(r"C:\Users\DGaard\Desktop\Gits\MoleculeSim\ownSim")

import molecules as mc
import forces as fc
import random
import copy

# Spawn random molecules montecarlo style

In [7]:

def generate_spheres(num_spheres, box_dimensions, radii, max_attempts):

  def check_overlap(new_sphere, existing_spheres):
    for sphere in existing_spheres:
        distance = np.linalg.norm(new_sphere[:3] - sphere[:3])
        if distance < new_sphere[3] + sphere[3]:
            return True
    return False

  spheres = []
  box_min = np.array([0, 0, 0])
  box_max = np.array(box_dimensions)
  attempts = 0

  for i in range(num_spheres):
    radius = radii[i]
    position = np.random.uniform(box_min + radius, box_max - radius)
    new_sphere = np.append(position, radius)

    attempts = 0
    while check_overlap(new_sphere, spheres):
        position = np.random.uniform(box_min + radius, box_max - radius)
        new_sphere = np.append(position, radius)
        attempts += 1

        if attempts > max_attempts:
          print("Unable to spawn points withing the box")
          return None

    spheres.append(new_sphere)

  return [mc.Molecule(np.array([x,y,z]),r) for (x,y,z,r) in spheres]

# Example usage:
num_spheres = 10
box_size = 1000
box_dimensions = [box_size, box_size, box_size]  # Define the box dimensions [x, y, z]
radius = 20
radii = [radius for _ in range(num_spheres)]
max_attempts = 100

resulting_spheres = generate_spheres(num_spheres, box_dimensions, radii,max_attempts)

print(resulting_spheres)
#if resulting_spheres != None:
#  for idx, sphere in enumerate(resulting_spheres):
#      print(f"Sphere {idx + 1}: Position {sphere[:3]}, Radius {sphere[3]}")
  


[<molecules.Molecule object at 0x0000018BE0191DE0>, <molecules.Molecule object at 0x0000018BE0193C40>, <molecules.Molecule object at 0x0000018BE0192BF0>, <molecules.Molecule object at 0x0000018BE0193100>, <molecules.Molecule object at 0x0000018BE01923E0>, <molecules.Molecule object at 0x0000018BE0193A90>, <molecules.Molecule object at 0x0000018BE01923B0>, <molecules.Molecule object at 0x0000018BE0193970>, <molecules.Molecule object at 0x0000018BE0193010>, <molecules.Molecule object at 0x0000018BE0193940>]


In [9]:
#mols = [mc.Molecule(np.array([x,y,z]),r) for (x,y,z,r) in resulting_spheres]

for i in resulting_spheres:
  print(i.pos, i.radius)

[924.39201026 745.85141975 444.55753538] 20.0
[164.19374649 769.02281619 544.18423296] 20.0
[243.30644256 594.91274833 170.40590349] 20.0
[436.10563275 563.25795629 610.93386629] 20.0
[497.61125614 156.523323   763.48880597] 20.0
[857.86282028 505.23327657 359.77656189] 20.0
[133.43569231 774.13153169 598.07731664] 20.0
[863.23074743 308.65007892 411.63320312] 20.0
[150.1590964   21.68975232 155.15407504] 20.0
[261.86420437 329.70080586 505.41712992] 20.0
