In [2]:
#IMPORTS 
import sys
import numpy as np
import matplotlib.pyplot as plt
sys.path.append(r"C:\Users\EmilR\Documents\GitHub\MoleculeSim\ownSim")

import molecules as mc
import forces as fc

In [3]:
# Parameters for universe initialization
box_const_size = 500
box_size = np.array([box_const_size,box_const_size,box_const_size]) #max coordinate values for universe
num_molecules = 5
num_steps = 10
radius  = 20
radii = [radius for _ in range(num_molecules)]

#other setup
seed = 1313

uni = mc.SimpleUniverse(box_size,num_molecules,radii,seed)

print(uni.get_state())

[[439.34046196 343.4064555  338.43604553]
 [418.53381511 177.5043083  181.52599947]
 [318.21448009 332.79261081 396.74184138]
 [312.55969602 113.43503826 368.07896403]
 [458.2758352   25.6154827  332.56561537]]


In [7]:
print(type(uni.molecules[0].pos[0]))

<class 'numpy.float64'>


In [4]:
#step loop
points = []

# Perform Simulation
for i in range(num_steps):
  #randomly select a molecule
  uni.make_step()
  #store intermediate results?
  points.append(uni.get_state())

In [5]:
#animate:
from __future__ import absolute_import, division, print_function
from mayavi import mlab
import numpy as np
import math


xs = np.array([inner_list[0] for sublist in points for inner_list in sublist]).reshape((num_steps,num_molecules)) #[inner_list[0] for sublist in test for inner_list in sublist]
ys = np.array([inner_list[1] for sublist in points for inner_list in sublist]).reshape((num_steps,num_molecules))
zs = np.array([inner_list[2] for sublist in points for inner_list in sublist]).reshape((num_steps,num_molecules))

#mlab.points3d(0,0,0)
plt = mlab.points3d(points[0][:, 0], points[0][:, 1], points[0][:, 2], resolution = 50)
mlab.axes()
text_position = (0,0,0)
text_actor = mlab.text3d(500,150, 510, "TESTING", scale = 40, color = (0,0,0))
@mlab.animate(delay = 200, ui = True, support_movie = True) #delay = 100
def anim():
    f = mlab.gcf()
    while True:
        #temp = "step: "
        for step in range(num_steps):
            x = points[step][:, 0]
            y = points[step][:, 1]
            z = points[step][:, 2]
            plt.mlab_source.set(x=x, y=y, z=z)
            text_actor.text = f"Frame: {step}"
            
            yield


anim()
mlab.show()